<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWlVdSvm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWlVdSvm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWlVdSvm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWlVdSvm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWlVdSvm\App_KernelDevDebugContainer([
    'container.build_hash' => 'WlVdSvm',
    'container.build_id' => 'acee1204',
    'container.build_time' => 1752656396,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWlVdSvm');
